# Generated by Django 5.2.4 on 2025-07-20 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 20, 12, 34, 56, 318243, tzinfo=datetime.timezone.utc)),
        ),
    ]
